name: ANTHONY DARIZ
favicon: null
layout_spectrum: 0.1426404279191047
typography_spectrum: 0.5980848181061447
title: ANTHONY DARIZ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#255569'
    - '#0b0301'
    - '#c3744b'
    - '#90401d'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
