name: ANTHONY DARIZ
favicon: null
layout_spectrum: 0.1426404279191047
typography_spectrum: 0.5980848181061447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.819488815497607
  lightness: 0.6805865506175905
  saturation: 0.3299589881207794
  rhythmicContrast: 0.4767554069403559
purpose: []
